ervice:
  type: ClusterIP

replicaCount: 1

serverBlock: |
  server {
    listen 0.0.0.0:8080;
    location / {
      return 200 '<html><body><h1>Hello from Bitnami NGINX via Argo CD</h1></body></html>';
    }
  }
